---
- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist

- name: Install openjdk-11-jdk
  become: true
  apt:
    name: openjdk-11-jdk
    state: latest

- name: update-java-alternatives
  become: true
  alternatives:
    name: java
    path: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
